apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: gcr.io/google/vproapp-image # Make sure this is the correct image
          ports:
            - name: vproapp-port
              containerPort: 8080

      initContainers:
        - name: init-mydb
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "until nslookup vprodb; do echo 'We are fetching db'; sleep 2; done",
            ]

        - name: init-memcache
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "until nslookup vprocache01; do echo 'We are fetching memcache'; sleep 2; done",
            ]
