apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb # Added value for the label ok
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb

    spec:
      containers:
        - name: vprodb
          image: yashpatel2307/vprofiledb
          volumeMounts: # Corrected key
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: # Corrected key
                  name: app-secret
                  key: db-pass
      nodeSelector:
        zone: ca-central-1a
      volumes: # Corrected key
        - name: vpro-db-data
          awsElasticBlockStore: # Corrected blockstore to BlockStore
            volumeID: vol-036b05377ccadb407
            fsType: ext4
      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm", "-rf", "/var/lib/mysql/lost+found"] # Added a missing '/' in the path
          volumeMounts: # Corrected key
            - mountPath: /var/lib/mysql
              name: vpro-db-data
